### ISSUE TITLE
autograd backward error 

### ISSUE THREAD

**Issue by Bontempogianpaolo1** [ml-research/NeSyXIL#3]
Hi!
I'm trying to execute your code for the first time and I obtain this error:

Pretrained slot attention model loaded!
train E00:   1% 1/70 [00:12<14:48, 12.88s/it]
Traceback (most recent call last):
  File "train_clevr_hans_concept_learner_xil_globalrule.py", line 545, in <module>
    main()
  File "train_clevr_hans_concept_learner_xil_globalrule.py", line 537, in main
    train(args)
  File "train_clevr_hans_concept_learner_xil_globalrule.py", line 389, in train
    _ = run_rrr(net, train_loader, optimizer, criterion, split='train', args=args,
  File "train_clevr_hans_concept_learner_xil_globalrule.py", line 291, in run_rrr
    loss.backward()
  File "/homes/gbontempo/.local/lib/python3.8/site-packages/torch/tensor.py", line 221, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/homes/gbontempo/.local/lib/python3.8/site-packages/torch/autograd/__init__.py", line 130, in backward
    Variable._execution_engine.run_backward(
RuntimeError: Trying to backward through the graph a second time, but the saved intermediate results have already been freed. Specify retain_graph=True when calling backward the first time.

Any suggest?

**Comment by wolfstam** [comment]
Heyho! Have you installed the cpatum package as explained in our readme? We had to modify exactly one line of code in captum such that the computational graph is stored. It sounds like the error is that you don't have our version of captum installed. Let me know if that helps.

**Comment by Bontempogianpaolo1** [comment]
I can't use the dockerfile and I 'm installing manually the dependencies... so following the dockerfile  I did 
"cd captum_xil/ && pip install -e . && cd .." But still, I'm having this issue

**Comment by wolfstam** [comment]
Could you maybe double check that in fact you are using our captum version when running the code and not a different version that was possibly co-installed?
